frontend/composables/useDashboardKeyProvider.ts

This PR:
- prevents from defaulting to the shared dashboard if you navigate to /dashboard

don't default to shared dashboard

---

frontend/assets/css/colors.scss
frontend/components/bc/table/BcTableTag.vue
frontend/components/block/table/BlockTableStatus.vue
frontend/components/dashboard/table/DashboardTableBlocks.vue
frontend/i18n/en.json

This PR:
- marks scheduled blocks that are before the current slot from the latest state as (probably) missed*

mark scheduled blocks of the past as probably missed

---

frontend/components/dashboard/SharedDashboardModal.vue
frontend/i18n/en.json

This PR
* Causes the "Shared Dashboard View"-modal to have a different text whenever the user already has at least 1 local/private dashboard

Improve text logic on shared dashboard view modal

---

frontend/assets/css/prime_menubar.scss
frontend/components/bc/ContentFilter.vue
frontend/components/bc/table/BcTableControl.vue
frontend/components/dashboard/DashboardHeader.vue

This PR:
Shows a hand cursor anywhere over the buttons + in the drop-down of the MenuBar:
Enlarges by +22% the input field of the filter at the top of tables, so that its placeholders are never truncated like that:

(NOBIDS) hand-cursor over dashboard menus + larger filter-input in tables

---

frontend/components/bc/BcIconToggle.vue

This PR:
- fixes the disabled toggle style on initial page load 
info for tester:
The chart toggle did not correctly apply the disabled style on intial page load ... it only worked after switiching between tabs

ensure disabled chart toggle uses the correct style

---

frontend/components/bc/footer/LinkList.vue
frontend/components/dashboard/DashboardHeader.vue
frontend/components/dashboard/table/DashboardTableBlocks.vue

This PR:
- routes the footer imprint to https://beaconcha.in/imprint
- removes the footer link to the API Docs
- fixes some paddings in the blocks table so that the rows have the same height as in the other tables
- fixes the transparent menu button (when a disabled button is a child of the main button on mobile)

several small fixes

---

frontend/components/pricing/PremiumProductBox.vue
frontend/components/pricing/PremiumViaAppBanner.vue
frontend/i18n/en.json
frontend/pages/pricing.vue
frontend/stores/useProductsStore.ts

This PR
* Implements the banner shown above the premium products on `/pricing` if the user subsribed to a premium product via app (iOS or Android)
For the reviewer:
The easiest way to show the banner is to change
https://github.com/gobitfly/beaconchain/blob/f9a1bcd4dd485bd33def1072496405062495fa8d/frontend/components/pricing/PremiumViaAppBanner.vue#L9
to
```ts
return (store === ProductStoreAndroidPlaystore || store === ProductStoreIosAppstore || true)
```

Implement PremiumViaAppBanner

---

frontend/components/dashboard/ValidatorSubsetModal.vue
frontend/components/dashboard/table/DashboardTableValidators.vue
frontend/utils/dashboard/validator.ts

This PR:
- prevents the ValidatorSubsetModal from modifying the Validator list in the Rewards Table
- sorts the table Validator ids in the Rewards Table

fix validator sorting in rewards table

---

frontend/components/dashboard/table/SummaryValue.vue
frontend/i18n/en.json
frontend/utils/format.ts

This PR
- correctly converts the luck average from nano seconds to a time duration

convert nano average to time duration

---

frontend/components/pricing/PremiumCompare.vue
frontend/i18n/en.json

This PR
* Hides all values, where we don't know what we can support yet, by writing "Soon" in italic instead

Hide timeframe related values on /pricing

---

frontend/components/bc/BcTooltip.vue
frontend/utils/html.ts

This PR:
- hides the Tooltip if any of it's scrollable parents is scrolled
- it also hides the tooltip on window resize 
Add. Infos:
- I left the `scrollContainer` (class provided by the outside) functionality in (even dough the new logic should tackle most cased needed)

hide tooltip in a scrolling scroll container

---

frontend/assets/css/prime_megamenu.scss
frontend/assets/css/variables.scss
frontend/components/bc/header/MainHeader.vue

This PR
- fixes the problem that on desktop on the initial page load the second row of the top header is too small and only fixes itself after hydration.

min height for nav bar 2 on desktop

---

frontend/components/pricing/PremiumAddonBox.vue

This PR
- takes the quantity into account for the addon price displays on the pricing pages

consider quantity for addon price

---

frontend/components/bc/header/MainHeader.vue

This PR changes the left side of the header **on mobile** :
- the brand name disappears,
- the logo becomes as high as the Signup button (30px),
- `v2 beta | {{ currentNetwork }}` is vertically centered and its font size becomes 14px.

(BIDS-3129) in the header: new layout on mobile screens

---

frontend/components/bc/BcTooltip.vue
frontend/components/dashboard/ValidatorSlotViz.vue
frontend/stores/useLatestStateStore.ts
frontend/stores/useUserStore.ts

Now:
- _BcTooltip.vue_ activates the listeners only when the tooltip is shown and turns them off when the tooltip is hidden.
This makes the UI to run less listeners than before (dozens on some pages).
- `refreshLatestState()` and `getUser()` return the data that they load in case of success or `undefined` in case of problem.
This allows `useAsyncData()` to call the API less often.

(NOBIDS) small improvements

---

frontend/assets/css/prime_megamenu.scss
frontend/components/bc/header/MegaMenu.vue
frontend/composables/useCurrency.ts

This PR:
- fixes the clickable area for the mega menu buttons
- improves performance (before the mega menu was reacreated on every latestState update): available currencies are now only updated if they really change

mega menu - fixing click area

---

frontend/components/bc/header/MainHeader.vue
frontend/stores/useUserStore.ts

If undefined data was received from the API, `getUser()` would return `undefined` to inform `useAsyncData` that it must recall the API from the client.
The user was not set to `undefined` in the meantime. This was a mistake.
Also:
The bottom border of the header should be visible when `NUXT_PUBLIC_SHOW_IN_DEVELOPMENT` is `"false"` and the screen is large.
It was not the case. Fixed.

(NOBIDS) small fix in the logic of getUser()

---

frontend/components/pricing/PremiumProductBox.vue
frontend/i18n/en.json

This PR
* Removes the "per dashboard" text for the validator amount on the `Guppy` card (as `Guppy` only has a single validator dashboard)

Remove "per dashboard" on guppy

---

frontend/components/bc/BcTooltip.vue
frontend/components/bc/toggle/MultiBar.vue
frontend/components/bc/toggle/MultiBarButton.vue
frontend/components/dashboard/ValidatorSlotViz.vue
frontend/components/slot/viz/SlotVizTile.vue
frontend/components/slot/viz/SlotVizTooltip.vue
frontend/components/slot/viz/SlotVizViewer.vue
frontend/composables/useDebounceValue.ts
frontend/i18n/en.json
frontend/stores/dashboard/useValidatorDashboardOverviewStore.ts
frontend/types/dashboard/slotViz.ts
frontend/types/multiBar.ts

This PR:
- adds a 'visible' icon to the Slot Viz filters: if disabled then no icons in the slot viz will  be shown 
- set the visible icon per default to hidden, if the dashboard has more then 60 validators. *
- adds tooltips to the Slot Viz filter icons
* Note: this will only be applied the first time the user navigates to the dashboard then it will be stored in the cookie

show hide icon

---

frontend/components/pricing/PremiumFeature.vue
frontend/components/pricing/PremiumProductBox.vue

This PR
* Increases some font sizes in the premium product boxes on `/pricing` on mobile
* Changes the `cost per validator` calculation from [`price` / `validators per dashboard`] to [`price` / `validators per dashboard` / `validator dashboards`] and shows an extra digit for that value
All changes have been discussed with @Buttaa.

Bids 3090/mobile adaptions for pricing

---

frontend/components/bc/footer/LinkList.vue

This PR
* Removes both the entries for the "API Pricing" and the "Advertise" links in the footer (changes discussed with @Buttaa )

Remove links to API pricing and advertise page (for now)

---

frontend/assets/css/prime.scss
frontend/components/bc/BcTooltip.vue
frontend/components/bc/toggle/MultiBar.vue
frontend/components/dashboard/ValidatorSlotViz.vue
frontend/components/slot/viz/SlotVizViewer.vue
frontend/i18n/en.json
frontend/stores/dashboard/useValidatorSlotVizStore.ts
frontend/types/network.ts

This PR:
- fixes the translation of the 'visible' icon in the slot filters
- refactors the slot viewer to handle more complex headers (while keeping the SlotVizViewer as dumb as encapsulated as possible) 
- adapts / implements the PrimeVue MulitSelcect (.p-multiselect) styles according to our styles
- Please note that the Total Group is separated from the rest of the List, this is not in the Layouts but was cross checked with the designer.
- adds network label to to the slot viz header
- adds an `?` icon to the header leading to the docu

Bids 3142/group filter for slot viz

---

frontend/components/slot/viz/SlotVizViewer.vue

This PR
- fixes an error thrown by a watch in the SlotVizViewer

fix watch error in SlotVizViewer

---

backend/pkg/api/data_access/dummy.go
backend/pkg/api/data_access/vdb_helpers.go
backend/pkg/api/data_access/vdb_slotviz.go
backend/pkg/api/handlers/common.go
backend/pkg/api/handlers/internal.go
frontend/stores/dashboard/useValidatorSlotVizStore.ts

Adds the `group_ids`  query parameter to the slot viz endpoint.

add group ids query parameter to dashboard slot viz endpoint

---

frontend/components/dashboard/table/DashboardTableValueDuty.vue

This PR
* fixes a typo in `VDBRewardesTableDuty` (=>`VDBRewardsTableDuty`) to solve one error popping up in npm

Fix VDBRewardesTableDuty

---

frontend/components/dashboard/chart/RewardsChart.vue

This PR:
- adds some padding to the Rewards Chart Legend
- sets the medium font weight for the x/y axis labels
- tries to fix the font family issue on mac by adding a backup font and default family (if we can't load it from the document) ... this is not tested on a mac and is just a wild guess.

Bids 2828/rewards chart font weight legend padding

---

frontend/components/bc/format/FormatPercent.vue
frontend/components/dashboard/OverviewBox.vue
frontend/components/dashboard/ValidatorOverview.vue
frontend/components/dashboard/table/DashboardTableSummary.vue
frontend/components/dashboard/table/DashboardTableValidators.vue
frontend/components/dashboard/table/SummaryDetails.vue
frontend/components/dashboard/table/SummaryStatus.vue
frontend/components/dashboard/table/SummaryValidators.vue
frontend/components/dashboard/table/SummaryValue.vue
frontend/components/dashboard/validator/subset/ValidatorSubsetModal.vue
frontend/components/dashboard/validator/subset/ValidatorSubsetSubHeader.vue
frontend/components/slot/viz/SlotVizViewer.vue
frontend/i18n/en.json
frontend/types/customFetch.ts
frontend/types/dashboard/overview.ts

This PR
Summary Table
- bigger Efficiency Icons 
- flip animation of status icons (current vs scheduled) and make the anmiations slower
- align icons in the validator header and row to the right on mobile view - so they align with the detail icons
- always show all inforamtion in the details, no matter if the column is visible or not
- remove 'Total' from 'Total missed rewards'
- remove bold from apr luck in details
- detail groups on mid size now get 50% width instead of a fixed width
- ... some more minor style fixes
Dashobar Overview
- add open validator list modal

Bids 3085/summary table fine tuning

---

frontend/assets/css/prime.scss
frontend/components/dashboard/validator/subset/ValidatorSubsetModal.vue
frontend/composables/useSwipe.ts

This PR:
- tries to prevent zoom/scrooling the background while swiping a dialog on mobile
- it also adds a little padding to the sub header of the validator list modal

prevent outside scroll while swiping dialog

---

frontend/components/dashboard/table/DashboardTableSummary.vue
frontend/components/dashboard/validator/subset/ValidatorSubsetModal.vue
frontend/stores/dashboard/useValidatorDashboardSummaryDetailsStore.ts
frontend/stores/dashboard/useValidatorDashboardSummaryStore.ts

This PR:
- enables sorting of the summary table 
- uses the correct `period` query param for the summary table calls
- sets the default sort of the summary table to efficiency

enable sorting, and fix period query param

---

frontend/components/dashboard/ValidatorSlotViz.vue
frontend/components/dashboard/table/SummaryDetails.vue
frontend/components/dashboard/table/SummaryValue.vue

This PR:
- hides empty groups in the slot viz
- hides the popout for the propsal row in the summary details

slotviz: hide empty groups, summary: hide proposal popout in details

---

frontend/components/dashboard/DashboardHeader.vue
frontend/components/dashboard/notifications/NotificationsManagementModal.vue
frontend/i18n/en.json
frontend/pages/notifications.vue

This PR
* Adds a draft for the "Manage Notifications" modal and opens it when the user clicks the "Manage Notifications" button
* Fixes the "Dashboard" icon used on `/notifications`

Bids 2857/manage notifications modal

---

frontend/components/dashboard/table/DashboardTableElDeposits.vue

This PR
- adds the missing data on the mobile view to the dashboard el deposits table
- from
- depositor
- tx hash

add missing mobile data for el deposits table

---

frontend/composables/useDashboardKeyProvider.ts
frontend/middleware/redirect.global.ts
frontend/pages/dashboard/[[id]]/index.vue
frontend/utils/dashboard/key.ts
frontend/utils/ether.ts
frontend/utils/misc.ts
frontend/utils/regexp.ts

This PR:
- implements redirecting of the validator dashboard if the validator list comes as query params
Example:
/dashboard?validators=5,0x832b8286f5d6535fd941c6c4ed8b9b20d214fc6aa726ce4fba1c9dbb4f278132646304f550e557231b6932aa02cf08d3
-> /dashboard/NSwweDgzMmI4Mjg2ZjVkNjUzNWZkOTQxYzZjNGVkOGI5YjIwZDIxNGZjNmFhNzI2Y2U0ZmJhMWM5ZGJiNGYyNzgxMzI2NDYzMDRmNTUwZTU1NzIzMWI2OTMyYWEwMmNmMDhkMw#summary

redirect validator dashboard with query params

---

frontend/components/pricing/PremiumCompare.vue
frontend/components/pricing/PremiumProductBox.vue
frontend/i18n/en.json

This PR,
based on [PR 539](https://github.com/gobitfly/beaconchain/pull/539)
- adapts the new API Chart Types for the pricing page. 
Note for tester: 
- the new API is not deployed yet so you will not see valid data for the chart props
- the heatmap part is reduced to the label with coming soon (compared to the Figma file) 
- values >= 1 day and < 1 year will be displayed in days (compared to the Figma file)

Bids 3186/pricing adaptations

---

frontend/components/bc/table/TablePager.vue
frontend/components/dashboard/validator/subset/ValidatorSubsetList.vue
frontend/components/validator/table/ValidatorTableStatus.vue
frontend/i18n/en.json

This PR:
- fixes the issue of wrapping text in the pager inside the validator subset modal
- moves the copybutton inside the list
- adds 'deposited' state to validator state translations

fix pager text wrap on validator subset modal and add deposited state

---

frontend/components/bc/BcDropdown.vue
frontend/components/bc/premium/BcPremiumGem.vue
frontend/components/bc/table/BcTableControl.vue
frontend/components/dashboard/chart/DashboardChartSummaryChartFilter.vue
frontend/components/dashboard/chart/SummaryChart.vue
frontend/components/dashboard/chart/SummaryChartTooltip.vue
frontend/components/dashboard/chart/TooltipHeader.vue
frontend/components/dashboard/table/DashboardTableSummary.vue
frontend/i18n/en.json
frontend/stores/useNetworkStore.ts
frontend/types/dashboard/summary.ts
frontend/utils/format.ts

This PR:
Implements the Summary 2.5 chart changes
- New Filter options
- aggregation (some options only available for permium users charts *)
- efficiency
- groups: Multi select + 2 special options (network average and total)
- data points now based on timestamp an no longer on epochs
This PR did not
- Test the chart with new data (the backend does not throw an error with the new options, but still returns the old data) -> currently the dates / epochs in the chart are wrong displayed as they are based on timestamps but get epochs from the backend. 
- Remove the `showInDevelopment` flag as the Chart should only be made public after tests against the new backend. 
- Implement loading of partial time frame loading. We will first see how the chart performs when loading all the data and only …

Bids 3162/summary chart v2 5

---

frontend/assets/css/prime_menubar.scss
frontend/components/dashboard/DashboardHeader.vue

This is a hack. Ideally buttons should be constructed in the correct format.
For example the text could define the `button size`, by having its own padding.
Preventing this issue.
See: BIDS-3200

Fix `clickable area` of `dashboard header buttons`

---

frontend/components/bc/searchbar/SearchbarMain.vue
frontend/components/bc/searchbar/SuggestionRow.vue
frontend/types/searchbar.ts

Now:
- the normal width of this cell is 126px as before: so all results look like they are organized in columns,
- in very rare cases when the content is bigger, the column can grow up to 140px (this breaks the harmony of the layout but it is rare and better than overflowing).
This can be observed by typing `0x9baA3244565d51D9C7897c0EB6679eD4890e536E` in the dialog box to add validators:
top : normal layout
bottom : layout for exceptionally large contents

(BIDS-3181) Adaptative width of cell 1 in the dropdown of the searchbar

---

frontend/components/playground/DashboardValidatorManageValidators.vue
frontend/components/validator/table/ValidatorTableStatus.vue
frontend/i18n/en.json
frontend/types/api/validator_dashboard.ts

New 'types` were added, some where renamend.
When including 'online` they should appear green.
When including 'offline` they should appear red.
Otherwise orange.
See: BIDS-3218

Adapt 'validator status' presentation

---

frontend/components/dashboard/table/DashboardTableSummary.vue
frontend/components/dashboard/table/SummaryDetails.vue

This PR
- hides the chart in the summary table in non prod
- fixes the scroll issue in the summary details table on mobile if there are multiple validators.

fix mobile summary detail scroll, hide chart in non dev mode

---

frontend/pages/dashboard/[[id]]/index.vue
frontend/stores/dashboard/useUserDashboardStore.ts
frontend/stores/dashboard/useValidatorDashboardBlocksStore.ts
frontend/stores/dashboard/useValidatorDashboardClDepositsStore.ts
frontend/stores/dashboard/useValidatorDashboardElDepositsStore.ts
frontend/stores/dashboard/useValidatorDashboardRewardsStore.ts
frontend/stores/dashboard/useValidatorDashboardSummaryStore.ts
frontend/stores/dashboard/useValidatorDashboardWithdrawalsStore.ts
frontend/utils/html.ts

This PR:
- makes sure that we don't set the shared dashboard key in the cookie dashboard
- fixes the issue in the Validator Summary tables when you switch from a shared dashboard to an empty dashboard .*
- fixes an error in the html utils where we check for an elements parent that sometimes cause an error in the console
.* to recreate the problem: Be not logged in. Create an empty dashboard (don't add validators). Open a shared dashboard and then click the 'go to dashboard' button in the bottom. Result before the bugfix: the shard key was put in the dashboard cookie and the summary table still showed the shared dashboard data. And sometimes this was leading to the browser to be frozen.

optimize the switch from a shared dashboard to /dashboard

---

frontend/components/dashboard/table/DashboardTableSummary.vue

This PR:
-  hides the 1h option in the dropdown of the summary table for non dev environment

summary table - hide 1h option in prod

---

frontend/i18n/en.json

Replace the placeholder tooltip text with the approved text.

Replace text for the tooltip. BIDS-3242.

---

frontend/components/dashboard/chart/SummaryChartTooltip.vue

This PR:
- adds a 0.5 opacity for non highlighted elements in the summary chart toolitp

summary chart tooltip: add opacity to non highlighted elements

---

frontend/components/dashboard/OverviewBox.vue

Request  to `DASHBOARD_VALIDATOR_INDICES` needed  `period query parameter`. 
For now it was `hard coded` to `last_24h`.
See: BIDS-3227

Fix `DashboardOverviewBox` does not show data

---

frontend/assets/css/colors.scss
frontend/assets/css/fonts.scss
frontend/assets/css/prime.scss

- Add necessery new colors and variable to follow the figma design.  BIDS-3206

Add `our` style changes to toast messages.  BIDS-3206.

---

frontend/components/dashboard/DashboardControls.vue
frontend/components/dashboard/table/DashboardTableSummary.vue
frontend/pages/dashboard/[[id]]/index.vue
frontend/stores/dashboard/useUserDashboardStore.ts

This PR: 
- enabled the 1h timeframe for the dashboard summary
- fixes a type error introduced by new props on the Validator Dashboard api types
- fixes a bug where we infinitely try to load our own validator dashboards when we encounter an error while loading the overview. 
- new logic only tries to load our own validator dashboard if the dashboard we tried was not our own (like shared) or was archived.
BIDS-3293

fix(dashboard): enable 1h timeframe, fix types error and loading bug

---

frontend/components/dashboard/table/SummaryDetails.vue

This PR:
- fixes the sorting of the attestation props in the validator dashboard summary details.

fix(dashboard): summary details attestation props sorting

---

frontend/components/dashboard/DashboardRenameModal.vue

This PR:
- adds the current dashboard name to the title in the rename dashboard dialog

feat(dashboard): add current name to rename dialog title

---

frontend/components/dashboard/chart/SummaryChart.vue

This PR:
- fixes the dashboard summary chart time handling
- omits the from value if you place the slider on the far left to prevent us from going to far in the past and cause a ws error
- refreshes the current slot that is based for the time frame range calculation when the user input changes
- prevents the UI from being locked if we get a WS error (previously the error message was placed over the UI and prevented the user from interacting with the chart to change the settings. 
BEDS-164

fix(dashboard): improve summary chart from handling

---

frontend/assets/css/prime_menubar.scss

This Pr:
- places the hover background on the correct element of the BcMenuBar elements

fix(dashboard): place hover menubar on the correct element

---

frontend/components/validator/table/ValidatorTableStatus.vue

This PR: 
- fixes the whitespace for the validator status in the Manage Validator Dialog

fix(dashbaord): fix whitespace of validator status in management modal

---

frontend/.vscode/settings.json
frontend/components/bc/header/MainHeader.vue

feat(mainHeader): make the `user menu panel` always open to the left

---

frontend/README.md
frontend/package.json

In order to run `dev server` with `https` we have to create a `certificate`. But this certificate is not `authorized` by a known and trusted `authority`. This is why we have to `disable` the rejection of that `certificate`
See: BEDS-97

chore: add `flag` to disable `unauthorized tls certs` to `dev script`

---

backend/pkg/api/data_access/user.go
backend/pkg/api/handlers/auth.go
backend/pkg/api/handlers/common.go
backend/pkg/api/handlers/internal.go
backend/pkg/api/handlers/public.go
backend/pkg/api/router.go
backend/pkg/api/types/user.go

This PR fixes the bug that prevents users from creating a dashboard, aswell as cleaning up the middlewares a bit. With these changes, the user ID (if available) is always loaded into the request context at the beginning. Further handlers should then only need to load user ID by context and throw unauthorized themselves, if they expect it to be in context.

(BEDS-274) fix auth

---

frontend/components/dashboard/table/SummaryDetails.vue

This PR:
- hides the reward and efficiency column if it is shown in the table row

fix(dashboard): hide reward and efficiency col in summary chart details

---

frontend/assets/css/prime_datatable.scss

This PR:
- adapts the loading spinner in the BcTable 
- makes sure that the loading spinner is not to far down in big tables
- makes sure that the table is still interactive while loading data.

fix(table): make sure spinner is not to far down at big tables

---

frontend/components/dashboard/chart/RewardsChart.vue

This PR:
- fixes the rewards chart
- display loading spinner
- check which min unit (ETH/GWEI/WEI) to use for the chart display.

fix(dashboards): rewards chart loading and min unit

---

frontend/components/dashboard/DashboardControls.vue
frontend/components/dashboard/DashboardHeader.vue

This PR:
- adapts the validator dashboard header
- removes the fixed button width for buttons
- reverses the sort of the manage buttons on mobile screen (when they are in a dropdown)
BEDS-285

fix(dashboard): remove fixed button width, revers manage button order

---

frontend/pages/pricing.vue

This PR:
- adds the import of the pricing page css vars that were removed by accident in a prev. PR

fix(pricing): fix broken css vars import

---

frontend/.vscode/settings.json
frontend/README.md
frontend/nuxt.config.ts
frontend/package.json

Nuxt can create `selfsinged certificates` on its own. This is especially heplful when checking out the repo or when using `git worktree`s feature, as there a fewer steps to get the dev server running.
See: BEDS-97

chore(checkout): using `nuxt`s `ssl handling`

---

.github/workflows/frontend-format-lint-typecheck.yml
frontend/.vscode/settings.json
frontend/app.vue
frontend/components/bc/searchbar/MiddleEllipsis.vue
frontend/components/bc/searchbar/SearchbarMain.vue
frontend/composables/useCustomFetch.ts
frontend/composables/useDashboardKeyProvider.ts
frontend/composables/useHashTabs.ts
frontend/nuxt.config.ts
frontend/package.json
frontend/plugins/bcLogger.ts
frontend/utils/environment.ts

Nuxt recommends not to run `linting` or `typechecking` on the `dev server`,
due to performacne reasons. As the `ide` should already catch `linting` or
`typeerrors`.
To improve DX for local `validation` before `pushing` you can run
`npm run validate` now (formatting, linting and typechecking)
See: https://nuxt.com/docs/guide/concepts/typescript#type-checking
See: BEDS-156

chore(ci): move typecheck to ci pipeline for better dev server performance

---

frontend/components/dashboard/ValidatorOverview.vue

This PR:
- moves the overview by 0 px to show the top border on IOS

fix(dashboard): move by 0 px to show top border on IOS

---

backend/pkg/api/data_access/dummy.go
backend/pkg/api/data_access/vdb.go
backend/pkg/api/data_access/vdb_management.go
backend/pkg/api/handlers/auth.go
backend/pkg/api/handlers/common.go
backend/pkg/api/handlers/internal.go
backend/pkg/api/types/data_access.go

This PR changes the parameter of a data access function, so that it can never take a validator set / guest dashboard as an argument. also renames some stuff for clarity.

(BEDS-313) don't pass VDBId struct in archiving middleware

---

frontend/package-lock.json
frontend/package.json

This Pr: 
- updates Nuxt to Version 3.12.4 
Reason for the Update: the 3.12.3 had an issue with the cookie reactivity (example: switching currency did not update the formatted values on the current page) 
Note: 
the update was done by modifying the `package.json` and not with `npx nuxi upgrade` as this leads to type problems in the current version.

chore: update nuxt to 3.12.4

---

frontend/components/dashboard/chart/RewardsChart.vue

This PR:
- labels the reward chart overlay as a date instead of the epoch
BEDS-309

fix(dashboard): label the time range overlay as date

---

frontend/assets/css/prime.scss
frontend/components/bc/BcTooltip.vue

This Pr:
- fixes the tooltip sizing
- borders around the groups in the validator dialog

fix: tootlip sizing and and border in validator list modal

---

backend/cmd/api/main.go
backend/go.mod
backend/go.sum
backend/pkg/api/data_access/healthz.go
backend/pkg/api/services/service_average_network_efficiency.go
backend/pkg/api/services/service_slot_viz.go
backend/pkg/api/services/service_validator_mapping.go
backend/pkg/api/types/data_access.go
backend/pkg/commons/db/migrations/clickhouse/20240821140310_status_reports.sql
backend/pkg/commons/metrics/metrics.go
backend/pkg/commons/types/config.go
backend/pkg/commons/utils/config.go
backend/pkg/commons/utils/uuid.go
backend/pkg/monitoring/constants/main.go
backend/pkg/monitoring/monitoring.go
backend/pkg/monitoring/services/base.go
backend/pkg/monitoring/services/clickhouse_epoch.go
backend/pkg/monitoring/services/clickhouse_rollings.go
backend/pkg/monitoring/services/db_connections.go
backend/pkg/monitoring/services/flaky_test_service.go

- adds deployment flags so staging/production can be cleanly seperated
- makes monitoring quite if in marked as development (the default if not manually set)
- adds run_id so healthz can catch incomplete excutions
- uses snowflakes during insertion to ensure order from single entity
- uses constants for statuses

Beds 306/healthz v2

---

frontend/.vscode/settings.json
frontend/components/dashboard/DashboardShareCodeModal.vue
frontend/composables/useCustomFetch.ts

…ators`
`validator ids` get encoded in `base64`.
Which triggerd the `data capacity limit` of the `qr library`.
So we use the `unencoded url version` (?validators=<validatorID or validatorIndex>),
as a workaround.
See: BEDS-350

fix(qrCode): use shorter url syntax for dashboards with many `valid… 

---

frontend/README.md
frontend/nuxt.config.ts

When we create our own `certs`, which have a `validity` of one year. We do not have to `click proceed` everytime we restart the `dev server`

chore: add `self signed` ssl certificates

---

frontend/assets/css/prime.scss

This PR is going to adjust styling to display the `accordion-header` correctly. 
BEDS-405

Adjust style for displaying the accordion content.

---

backend/pkg/api/data_access/vdb_slotviz.go

sources the head epoch from the slot viz duties response to avoid data races when setting the `latestEpoch` cached variable

fix(dashboard): source head epoch from slot viz duties response

---

frontend/components/BcFeatureFlag.vue
frontend/components/bc/BcButtonText.vue
frontend/components/notifications/NotificationsOverview.vue
frontend/locales/en.json
frontend/pages/notifications.vue
frontend/stores/notifications/useNotificationsOverviewStore.ts
frontend/types/customFetch.ts

- add `NotificationsDashboardNotificationsOverview` component to display data from the notifications-overview API call.
- introduce `useNotificationsOverviewStore` hook to fetch and manage `notifications-overview` data.
- extende `customFetch` to support the new `notifications-overview` API endpoint.
- add translations for the `NotificationsDashboardNotificationsOverview` component.
- add `BcButtonText` component.
See: BEDS-335

feat: add Dashboard Notifications Overview Component and API Integration  

---

frontend/composables/useCustomFetch.ts

Flag was not linked to `environment variable`
See: e7b05

fix(customFetch): add `flag` to get `mocked data`

---

frontend/components/notifications/management/NotificationsManagementSubscriptionDialog.vue
frontend/package.json

Pluralization rule needs type `number` instead of `string`
See: BEDS-609

BEDS-609/fix-text-attestation-missed

---

backend/pkg/api/auth.go
backend/pkg/api/data_access/dummy.go
backend/pkg/api/router.go

- **feat: add sliding expiration for sessions, extend session length to 1 year**
- **fix: implement boundaries for all mocked float values (between 0 and 1)**

BEDS 444/prolong sessions

---

frontend/.vscode/settings.json
frontend/components/notifications/NotificationsMachinesTable.vue

- Pass the `data-key` prop to ensure proper handling in TreeTable. This is required by the `ui library`.
See: BEDS-256

fix(NotificationMachinesTable): add `machines` data key

---

backend/pkg/api/handlers/public.go

fix: consistent naming for webhook notification parameters

---

backend/pkg/api/data_access/archiver.go
backend/pkg/api/data_access/block.go
backend/pkg/api/data_access/data_access.go
backend/pkg/api/data_access/dummy.go
backend/pkg/api/data_access/header.go
backend/pkg/api/data_access/mobile.go
backend/pkg/api/data_access/notifications.go
backend/pkg/api/data_access/vdb_management.go
backend/pkg/api/handlers/auth.go
backend/pkg/api/handlers/backward_compat.go
backend/pkg/api/handlers/handler_service.go
backend/pkg/api/handlers/input_validation.go
backend/pkg/api/handlers/internal.go
backend/pkg/api/handlers/middlewares.go
backend/pkg/api/handlers/public.go
backend/pkg/api/types/data_access.go

- **refactor: pass and use context everywhere**
- **refactor: move context keys to types pkg**
- **feat: store dashboard id in context in archiving middleware**
- **feat: implement mock_seed query param**

BEDS 868/mock seed

---

backend/pkg/api/handlers/public.go

fix: cap do not disturb timestamp if greater than maxInt32

---

frontend/components/notifications/management/NotificationsManagementNetwork.vue

As the `multichain feature` is not implemented yet, we are using `environment variables` to identify the current network
See: BEDS-898

fix(NotificationsManagementNetwork): `currentNetworkId` by using `environment variable`

---

frontend/components/notifications/NotificationsTableEmpty.vue
frontend/components/notifications/management/NotificationsManagementDashboards.vue
frontend/composables/notifications/useNotificationsManagementDashboards.ts
frontend/locales/en.json
frontend/stores/notifications/useNotificationsManagementStore.ts

Remove `Click here to set notifications` text for `empty tables`, when there are already `notification settings` for the specifc table

empty state for `notification tables` when there are `settings`

---

backend/pkg/api/data_access/general.go
backend/pkg/api/data_access/notifications.go
backend/pkg/api/data_access/vdb_blocks.go

I rewrote the applySortAndPagination method.
It already had some handling for NULL values for WHERE but it was not correct.

Fixed pagination for NULL entries in the DB

---

frontend/.vscode/settings.json
frontend/components/dashboard/table/DashboardTableSummaryDetails.vue

This is a `quick-fix`, temporarily remove `missed rewards` per request.
See: BEDS-923

refactor(DashboardTableSummaryDetails): remove `missed rewards`

---

backend/pkg/api/data_access/notifications.go
backend/pkg/api/types/notifications.go
frontend/components/notifications/NotificationsDashboardDialogEntity.vue
frontend/types/api/notifications.ts

refactor: match dashboard notification detail to notification event name

---

backend/pkg/api/enums/notifications_enums.go

When we switched from epoch to ts I missed to change this enum method.

Fixed column name for time ordering

---

backend/pkg/api/data_access/vdb_blocks.go

The `blocksDs` and `scheduledDs` subqueries now also directly apply the limitations from pagination and limit with ordering.

Added conditions to the subqueries that use union

---

frontend/components/dashboard/table/DashboardTableBlocks.vue

Removes sort from proposer rewards in validator dashboard blocks table.
Before PR:
After PR:

refactor(DashboardTableBlocks): remove sortable attribute from rewards

---

backend/pkg/api/data_access/vdb_blocks.go

I could probably implement WHERE/ORDER/LIMIT handling for status and block sorting for scheduled blocks as a special handling but since there should never be more than a few dozen scheduled proposals it does not seem worth it to me.

Removed limits for scheduled blocks for some sortings
