- frontend/components/pricing/PremiumAddonBox.vue
This PR floors the max addon count
> floor the addon limit

- frontend/components/bc/CookieModal.vue
- frontend/components/dashboard/SharedDashboardModal.vue
This PR
* Adapts the styling of the "Shared Dashboard View"-modal and adds a dismiss button
* Uses the dismiss styling for the "Only Necessary" button on the cookie modal
> Bids 3125/restyle shared dashboard view modal

- frontend/components/dashboard/table/DashboardTableSummary.vue
This PR
- hides the 3 bigger efficiency cols at a time instead of all once
> hide one efficiency column at a time

- frontend/app/router.options.ts
- frontend/components/dashboard/DashboardHeader.vue
- frontend/composables/useCustomFetch.ts
- frontend/composables/useDashboardKeyProvider.ts
- frontend/composables/useHashTabs.ts
- frontend/pages/dashboard/[[id]]/index.vue
- frontend/types/hashTabs.ts
This PR:
- introduces a new composable to select tabs based on the url hash
- adds this composable to the dashboard page
Note to the tester: url hashes are not sent to the server and therefor not available during SSR
> use url hash to select tab

- frontend/components/dashboard/table/SummaryDetails.vue
This PR
- fixes validator truncation in the 2.5 summary details
> truncate validator list in summary details

- frontend/components/pricing/PremiumCompare.vue
- frontend/i18n/en.json
This PR
* Adds a row for "Bulk Adding" to the compare component used on `/pricing`
* Re-factors the compare component slightly
> Add "Bulk Adding" to premium compare

- frontend/components/dashboard/creation/DashboardCreationNetworkMask.vue
- frontend/components/dashboard/creation/DashboardCreationTypeMask.vue
When button is disabled show: "Coming soon" otherwise the `network name`
See: BIDS-3205
> Change subtext of  `dashboard creation modal`

- frontend/components/slot/viz/SlotVizTooltip.vue
> Fix overflowing text in `SlotVizToolTip`

- frontend/components/notifications/DashboardsTable.vue
- frontend/components/notifications/DashboardsTableEmpty.vue
- frontend/components/notifications/DashboardsTableItemDashboard.vue
- frontend/i18n/en.json
- frontend/pages/notifications.vue
- frontend/public/mock/notifications/dashboards.json
- frontend/stores/dashboard/useUserDashboardStore.ts
- frontend/stores/notifications/useNotificationsDashboardStore.ts
- frontend/types/customFetch.ts
- frontend/types/notifications/dashboards.ts
- mock Network Switcher
- mock table data
- mock entity popout
- implement table
See: BIDS-2848
> BIDS-2848: Implement NotificationsDashboardsTable

- frontend/components/bc/BcTooltip.vue
- frontend/components/playground/PlaygroundIcons.vue
This PR:
- Tries to align the tooltip arrow icon with it's parent as good as possible  - like on the borders of the browser.
> align arrow icon for tooltips on the border of the screen

- frontend/assets/css/fonts.scss
**BIDS-3233**
Updating the font-weight for the `--tooltip_text_font_weight ` for better user experience.
> Update the font-weight. BIDS-3233.

- frontend/components/bc/header/MainHeader.vue
- frontend/components/bc/header/MegaMenu.vue
To try it:
1. Use a mobile view,
2. Log out. The login/signup buttons take all the room in the header so the currency selector is in the burger menu.
3. Log in. The currency selector is now in the header because there is room for it.
> (BIDS-3229) Shows the currency selector in the header (rather than burger menu) if there is enough room

- frontend/components/slot/viz/SlotVizTooltip.vue
- frontend/i18n/en.json
This is a proposal.
In this version, the changes require 7 additional lines of code and the code is more complicated.
> (BIDS-3044) Slotviz tooltips: slot numbers open slot pages -- version B

- frontend/components/user/settings/UserSettingsDeleteAccount.vue
- frontend/i18n/en.json
This PR
* Shortens and harmonizes the warnings on the delete modal for "Delete Dashboard" and "Delete Account"
> Shorten and harmonize delete warnings

- frontend/components/bc/PageWrapper.vue
- frontend/components/bc/header/HeaderLogo.vue
- frontend/components/bc/header/MainHeader.vue
- frontend/i18n/en.json
- frontend/middleware/redirect.global.ts
- frontend/pages/login.vue
- frontend/pages/register.vue
- frontend/types/header.ts
This PR
- improves the designs of the login and registration pages,
- empties the header for these pages, only the logo remains.
> (BIDS-3256) Login and Signup pages - redesign

- backend/pkg/commons/templates/mail/layout.html
- frontend/components/bc/footer/CopyrightAndVersion.vue
This PR:
- fixes the bitfly explorer label in the footer and the email notification
> fix(explorer): bitfly explorer label

- frontend/components/dashboard/table/DashboardTableRewards.vue
This PR:
- remove the dev flag to enable the rewards chart for production
> fix(dashboard): enable rewards chart

- frontend/components/dashboard/chart/SummaryChart.vue
This PR:
- Tries to optimize the range selection in the dashboard summary chart
- changing the MAX_DATA_POINTS to 199
- introducing a min range
- refactoring the time range checking logic
- increasing the default range for the Epoch Range 
BEDS-217
> fix(dashboard): make summary chart range selection more resilient

- frontend/assets/css/prime.scss
- frontend/components/bc/BcDropdown.vue
- frontend/components/bc/BcMultiSelect.vue
- frontend/components/dashboard/chart/DashboardChartSummaryChartFilter.vue
- frontend/i18n/en.json
This PR:
- fixes the font size of the summery chart filter dropdowns
BEDS-206
> fix(dashboard): summary chart filter font size

- frontend/components/bc/table/BcTable.vue
- frontend/components/dashboard/table/DashboardTableEmpty.vue
- frontend/components/dashboard/table/DashboardTableSummary.vue
- frontend/locales/en.json
- frontend/pages/dashboard/[[id]]/index.vue
This PR:
- adds message for when the vlidators are added but do not fulfill any tasks.
- adds text and Component for the message
> Beds 162/display message if api returns empty

- backend/pkg/api/data_access/vdb_withdrawals.go
> BEDS-311/port_InternalGetValidatorDashboardTotalWithdrawals_to_clickhouse

- backend/pkg/api/data_access/vdb_summary.go
I also cleaned up the method by using goqu to avoid duplicated query parts.
> Fixed GetValidatorDashboardGroupSummary for empty

- frontend/components/bc/tab/BcTabList.vue
This PR:
- makes the Tabs scrollable again
BEDS-344
> fix: make tabs scrollable again

- frontend/assets/css/prime.scss
- frontend/components/bc/BcMultiSelect.vue
This PR:
- fixes the Styles after the PrimeVue Update for 
- Select
- MultiSelect
> fix: multi + select primevue update styles

- frontend/assets/css/prime.scss
- frontend/components/bc/table/TablePager.vue
This PR:
- makes sure that the last row does not prevent the table pager buttons to be clickable.
> fix(table): fix interaction of table pager buttons on big screen

- backend/pkg/api/data_access/dummy.go
refactors dummy service to use generic func to avoid code duplication
> (BEDS-347) refactor dummy

- backend/pkg/api/data_access/dummy.go
- backend/pkg/api/data_access/vdb.go
- backend/pkg/api/data_access/vdb_deposits.go
- backend/pkg/api/handlers/public.go
removes unused search param from deposit endpoints
> (BEDS-409) deposit endpoints: remove search param

- frontend/components/bc/searchbar/SearchbarMain.vue
Set HTML attributes to prevent popups from third-party apps.
BEDS-368
> Set HTML attributes.

- frontend/assets/css/prime.scss
fix: :lipstick: Add temporary workaround to fix shifting display issue and background color when opening the modal.
BEDS-406
> 💄Temporary Fix: Resolve Display Shift and Background Color Issue When Opening Modal

- .github/workflows/backend-publish-docker.yml
- backend/pkg/commons/db/ens.go
see https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2951
> Beds 90/fix ens long names

- .github/workflows/frontend-publish-docker.yml
> ci: fix docker-image-tags

- backend/cmd/eth1indexer/main.go
this is really just a port over from v1
> refactor(eth1indexer): update ens in seperate go-routine

- backend/pkg/exporter/modules/rocketpool.go
> chore(exporter): report status of rocketpoolExporter

- frontend/.vscode/settings.json
- frontend/assets/css/colors.scss
- frontend/components/bc/BcDropdownToggle.vue
- frontend/components/bc/BcToggle.vue
- frontend/components/notifications/management/NotificationsManagementClients.vue
- frontend/components/notifications/management/NotificationsManagementModal.vue
- frontend/locales/en.json
- frontend/stores/notifications/useNotificationsManagementStore.ts
- frontend/types/customFetch.ts
- add `focus style` to `BcToggle`
- add `clients tab` to `NotificationsManagement Modal`
- add component `BcDropdownToggle`
> BEDS-188/notifications-management-clients

- frontend/components/bc/BcButton.vue
- frontend/components/bc/BcButtonIcon.vue
- frontend/components/bc/BcText.vue
- frontend/components/dashboard/DashboardValidatorOverview.vue
- frontend/components/notifications/management/NotificationsManagementDashboards.vue
- frontend/components/notifications/management/modal/NotificationsManagementModalDashboardsDelete.vue
- frontend/composables/notifications/useNotificationsManagementDashboards.ts
- frontend/locales/en.json
- frontend/types/customFetch.ts
- refactor: rename prop `srText` to `screenreaderText` better clarity
- feat(notifications): add `delete notifications` for `dashboard notifications`
See: BEDS-559
> feat(notifications): add `delete notifications` for `dashboard notifications`

- frontend/.vscode/settings.json
- frontend/components/notifications/DashboardsTable.vue
- frontend/components/notifications/NotificationsNetworkTable.vue
- frontend/components/notifications/NotificationsRocketPoolTable.vue
- frontend/locales/en.json
- frontend/middleware/redirect.global.ts
- frontend/pages/notifications.vue
- frontend/utils/environment.ts
- frontend/utils/logger.ts
- refactor(notifications): fix missing network tab title
- chore(notifications): translate event types for dashboard table
- chore(NotificaiontsNetworkTable): remove search
- fix(middleware): add missing `external` prop for all redirections to `v1`
- chore(NotificationsNetworkTable): fix data in table due to latest design changes
> Beds 97/fix issues notifications

- backend/pkg/api/data_access/notifications.go
- backend/pkg/api/enums/notifications_enums.go
> refactor: rename sort col name for dashboard notifications table

- backend/cmd/api/main.go
- backend/pkg/api/api_test.go
- backend/pkg/api/data_access/notifications.go
- backend/pkg/api/handlers/auth.go
- backend/pkg/api/handlers/common.go
- backend/pkg/api/handlers/public.go
- backend/pkg/api/router.go
- **refactor: merge validator dashboard rocketpool nodes endpoint into rocketpool table call**
- **fix: handle floating point error when putting notification settings**
- **fix: don't fetch paired devices with null id**
- **feat: implement basis for getting mocked api data**
> BEDS 605/mock

- backend/pkg/commons/utils/utils.go
- backend/pkg/notification/sending.go
> chore(notifications): warn on noncritical errors and cap body

- frontend/components/notifications/management/NotificationsManagementGeneralTab.vue
> fix(notifications): update `overview` when changing `general settings`

- backend/pkg/api/data_access/notifications.go
- backend/pkg/api/types/notifications.go
- frontend/types/api/notifications.ts
> feat: add dashboard name to dashboard settings response

- frontend/components/notifications/NotificationsDashboardDialogEntity.vue
- frontend/locales/en.json
Peter decided to remove `group_offline`, `group_offline_reminder` and `group_back_online`
> fix(notifications): adapt to `type changes`

- frontend/.vscode/settings.json
- frontend/components/notifications/NotificationsDashboardDialogEntity.vue
- frontend/components/notifications/management/NotificationsManagementDashboards.vue
> fix: show correct `dashboard` and `group names`

- frontend/locales/en.json
> refactor: fix `translation` for `attestation missed`

- backend/pkg/api/data_access/notifications.go
I can't test for wrong behaviour and then correct behaviour but it would make sense that this fixes it.
> Get the data from the correct database

- backend/pkg/api/auth.go
- backend/pkg/api/data_access/dummy.go
- backend/pkg/api/data_access/notifications.go
- backend/pkg/api/handlers/handler_service.go
- backend/pkg/api/handlers/public.go
- **feat: implement proper test notification handling**
- **feat: log requesting user id when logging err**
> BEDS 94/test notif

- frontend/.vscode/settings.json
- frontend/components/dashboard/table/DashboardTableValidators.vue
> feat(DashboardTableValidators): add `information summary` for user

- backend/pkg/api/data_access/notifications.go
- backend/pkg/api/types/notifications.go
- frontend/components/notifications/NotificationsOverview.vue
- frontend/types/api/notifications.ts
- **refactor: rename last 24h email count**
- **feat: add next email count reset ts to notification overview**
> BEDS 870/email reset

- backend/pkg/api/handlers/handler_service.go
- backend/pkg/api/handlers/public.go
> fix: map db notification event names to api defined names

- backend/pkg/api/data_access/vdb_summary.go
- backend/pkg/api/types/common.go
- frontend/components/dashboard/table/SummaryValue.vue
- frontend/types/api/common.ts
- frontend/utils/format.ts
> refactor: change luck time fields to uint64

- backend/pkg/api/data_access/archiver.go
- backend/pkg/api/data_access/notifications.go
- backend/pkg/api/data_access/vdb_rewards.go
- backend/pkg/api/data_access/vdb_summary.go
> fix: wrap errors properly in data access

- backend/pkg/api/types/validator_dashboard.go
- frontend/types/api/validator_dashboard.ts
> feat: add validator count field to group summary

- frontend/components/dashboard/table/DashboardTableValidators.vue
- frontend/components/dashboard/table/SummaryValue.vue
- frontend/utils/dashboard/validator.ts
On DashboardTableSummary
See: BEDS-649
> fix: show `3 validator indexes` or correct `validator count`

- backend/pkg/api/handlers/input_validation.go
- backend/pkg/api/handlers/search_handlers.go
> feat: add validator list to search types

- backend/pkg/api/handlers/handler_service.go
> fix: sanitize input on intOrString Fields

- backend/pkg/api/data_access/dummy.go
- backend/pkg/api/data_access/vdb.go
- backend/pkg/api/data_access/vdb_management.go
- backend/pkg/api/handlers/internal.go
- backend/pkg/api/handlers/public.go
- backend/pkg/api/router.go
> feat: add endpoint for deleting all valis in a validator dashboard group

- frontend/locales/en.json
To make it easier to understand for user what the information belongs to.
See: BEDS-853
> refactor(notifications): add `rpl` to `labels`

- frontend/components/dashboard/DashboardValidatorManagementModal.vue
> fix(DashboardValidatorManagmentModal): check if user has `bulk adding`
